name: Format Code and Generate API Docs

on:
  workflow_call:
  
jobs:
  format-and-generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Create .env file from example
        run: cp .env.example .env
          
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      
      - name: Run code formatter (composer fmt)
        run: composer fmt
      
      - name: Generate API Documentation (composer run gen-api-doc)
        run: composer run gen-api-doc

      - name: Commit all changes (Format and Docs)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'ci: apply formatting and generate latest OpenAPI documentation'